name: Website Builder
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/website-builder.yml
      - new/**
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node
        run: |
          sudo apt install nodejs

      - name: Build website
        run: |
          pwd
          cd new
          npm install
          npm run build
          cd dist
          rm -f ../../deepracer-console-new.zip && zip -r ../../deepracer-console-new.zip .
          cd ../../

      - name: Create deb package
        run: |
          ./deepracer-build-pkg.sh

      - name: Create a draft release
        run: |
          DEBFILE=$(compgen -G dist/aws-deepracer-device-console*.deb)
          gh release create --draft --prerelease --title "Branch: ${{ github.ref_name }}, Job: ${{ github.run_id }}" --target ${{ github.ref_name }} --notes "Draft Release from Branch: ${{ github.ref_name }}, Action Job id: ${{ github.run_id }} Auto-generated draft release from workflow https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" v0.${{ github.run_id }}  deepracer-console-new.zip $DEBFILE
          rm deepracer-console-new.zip
          rm $DEBFILE
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
